version: "3"
services:
  db:
    image: postgres:14  # https://hub.docker.com/_/postgres
    ports:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app

  web:
    build: #build the image from a dockerfile
      context: ./backend 
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8001:8001"
      - "5433"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment: #You can set environment variables in a service’s containers with the ‘environment’ key, just like with docker run -e VARIABLE=VALUE 
                #https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers
      # This optional variable can be used to define another location -
      # like a subdirectory - for the database files.
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=db
      # This optional environment variable is used in conjunction with POSTGRES_PASSWORD
      # to set a user and its password. This variable will create the specified user with superuser
      # power and a database with the same name. If it is not specified, then the default user of
      # postgres will be used.
      - POSTGRES_USER=postgres
      # This environment variable is required for you to use the PostgreSQL image.
      # It must not be empty or undefined. This environment variable sets the superuser
      # password for PostgreSQL. The default superuser is defined by the POSTGRES_USER environment variable.
    volumes:
      - ./backend/app:/app
      - ./backend/assets:/assets
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/app
      - DATABASE_TEST_URL=postgresql://postgres:password@db:5432/app_test
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
      - 
volumes:   #https://docs.docker.com/compose/compose-file/#volumes
  app-db-data: 
